site_name: RecoveryBox
site_url: https://recoverybox.fr/
site_description: Offline emergency server for essential resources
repo_url: https://github.com/mr-dgidgi/recoverybox
repo_name: mr-dgidgi/RecoveryBox

theme:
  name: material
  language: fr
  logo: images/RB_logo_light.svg
  favicon: images/RB_logo_light.svg
  palette:
    # Day
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Night
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra_css:
  - stylesheets/recoverybox-theme.css

extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Français
      link: /fr/
      lang: fr
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mr-dgidgi/recoverybox
      name: GitHub

plugins:
  - search
  - glightbox
  - blog:
      blog_dir: fr/blog
      post_date_format: full
      post_readtime: true
      archive: false
      categories: false
  - blog:
      blog_dir: en/blog
      post_date_format: full
      post_readtime: true
      archive: false
      categories: false
nav:
  - Français:
    - Accueil: fr/index.md
    - Actualités: fr/blog/index.md
    - Wiki: https://recoverybox.fr/wiki/fr/
  - English:
    - Home: en/index.md
    - Blog: en/blog/index.md
    - Wiki: https://recoverybox.fr/wiki/en/

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
